plugins {
    id 'dev.hybridlabs.fabric'
    id 'org.jetbrains.kotlin.jvm'
}

dependencies {
    implementation("dev.hybridlabs.hapi:hapi-common-1.21.1:1.1.0")
    modImplementation("dev.hybridlabs.hapi:hapi-fabric-1.21.1:1.1.0")

    modImplementation "software.bernie.geckolib:geckolib-fabric-$geckolib_version"
}

fabricApi {
    configureDataGeneration {
        setModId("$mod_id")
        outputDirectory = file("src/generated/resources")
    }
}

publishMods.platforms.configureEach {
    requires 'fabric-api', 'fabric-language-kotlin', 'geckolib', 'hybrid-api'
    optional 'hybrid-aquatic'
}
